### ISSUE TITLE
Division by zero - message

### ISSUE THREAD

**Issue by janbarasek** [mathematicator-core/calculator#1]
```yaml
translate:
	cz:
		divisionByZero: 'Představ si, že máš rozdělit {$count} {count|$count:jablko:jablka:jablek} mezi 0 lidí. Kolik dostane každý? Vidíš... nedává to moc smysl.'
	en:
		divisionByZero: 'Imagine you have {$count} {count|$count:apple:apples} and you will assign to 0 people. How many everybody get? As you see, it does not sense.'
```
